-- Query1 ----
;

select E.F_NAME,E.L_NAME
from EMPLOYEES AS E INNER JOIN JOB_HISTORY AS J ON E.EMP_ID=J.EMPL_ID
where J.DEPT_ID ='5';

-- Query 2 ----
;
select E.EMP_ID,E.L_NAME,E.DEP_ID,D.DEP_NAME
from EMPLOYEES AS E LEFT OUTER JOIN DEPARTMENTS AS D ON E.DEP_ID=D.DEPT_ID_DEP AND YEAR(E.B_DATE) < 1980;

-- Query 3 -----
;

select E.F_NAME,E.L_NAME,D.DEP_NAME
from EMPLOYEES AS E FULL OUTER JOIN DEPARTMENTS AS D ON E.DEP_ID=D.DEPT_ID_DEP and E.SEX = 'M';

